
(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const page=document.body.dataset.page||'home';
const header=$('[data-header]'), progress=$('[data-progress]');
let raf=false;
const onScroll=()=>{if(raf)return;raf=true;requestAnimationFrame(()=>{header?.classList.toggle('is-scrolled',scrollY>24);if(progress){const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);progress.style.transform=`scaleX(${Math.min(1,scrollY/max)})`;}if(page==='home'&&!reduce){const hero=$('[data-hero-image]');if(hero&&scrollY<innerHeight*1.2)hero.style.transform=`scale(1.055) translateY(${scrollY*.035}px)`;}raf=false;});};
addEventListener('scroll',onScroll,{passive:true});onScroll();

const menu=$('[data-menu-toggle]'),nav=$('[data-nav]');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');document.body.classList.toggle('nav-open',open);menu.setAttribute('aria-expanded',String(open));});
$$('.nav a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('is-open');document.body.classList.remove('nav-open');menu?.setAttribute('aria-expanded','false')}));

if(!reduce&&window.gsap){
  gsap.set('.reveal',{opacity:0,y:18});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){gsap.to(e.target,{opacity:1,y:0,duration:.72,ease:'power3.out'});io.unobserve(e.target)}}),{rootMargin:'0px 0px -8%',threshold:.08});$$('.reveal').forEach(el=>io.observe(el));
  if(page==='home'){const tl=gsap.timeline({defaults:{ease:'power3.out'}});tl.from('[data-hero-line]',{opacity:0,y:42,duration:.72,stagger:.1}).from('[data-hero-piece]',{opacity:0,y:12,duration:.5,stagger:.07},'-=.38');}
}else{$$('.reveal').forEach(el=>{el.style.opacity=1;el.style.transform='none'})}

// Fast, restrained number count.
if(!reduce&&'IntersectionObserver'in window){const cio=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(el.dataset.count),suffix=el.dataset.suffix||'';const start=performance.now(),dur=700;const tick=t=>{const p=Math.min(1,(t-start)/dur),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=v+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);cio.unobserve(el)}),{threshold:.5});$$('[data-count]').forEach(el=>cio.observe(el));}

const idxLabel=m=>`${m.type==='spm'?'SPM':'RTF'} / ${String(machineArchive.filter(x=>x.type===m.type).indexOf(m)+1).padStart(2,'0')}`;
const cat=categoryNames;
const searchText=m=>[m.title,m.customer,m.control,m.note,cat[m.category],archiveTypeName[m.type]].filter(Boolean).join(' ').toLowerCase();
const photoCount=machineArchive.filter(m=>m.media?.length).length;
const placeholder=(label='VSK / ARCHIVE')=>`<div class="blueprint-placeholder"><span>VSK / ENGINEERING ARCHIVE</span><b>${label}</b><i></i></div>`;

// Feature/project catalog data.
const projectOrder=['zcut','slotting','airleak','rod','jig','kellenberg','vertical','wheel','facing','paint','udrill','oven','tabletop','conveyor','spindle'];
const projectSubtitle={zcut:'0.02 mm tolerance reference',slotting:'Four-axis servo machine family',airleak:'Festo servo testing reference',rod:'Siemens 802D · 2-axis CNC',jig:'PLC / HMI + 3 servo axes',kellenberg:'Fanuc 0i-TF Plus',vertical:'PTFE rod · 900 mm reference',wheel:'20 μm alignment reference',facing:'12 second cycle reference',paint:'Process equipment · Prestige',udrill:'Original VSK project image',oven:'Original image + motion clip',tabletop:'PTFE rods · ±0.1 mm reference',conveyor:'Centerless grinding feeding',spindle:'Machine-tool interface detail'};
const projectTile=(id,klass='')=>{const d=featureData[id],media=d.media?.[0];return `<button class="${klass}" type="button" data-feature-open="${id}" id="${id}">${media?`<img src="${media}" alt="${d.title}" loading="lazy" />`:placeholder(id.toUpperCase())}<span class="tile-copy"><span>${d.index||d.type}</span><strong>${d.title}</strong><small>${projectSubtitle[id]||d.summary}</small></span></button>`};
if($('[data-home-projects]'))$('[data-home-projects]').innerHTML=['zcut','slotting','airleak','rod','jig','kellenberg'].map(id=>projectTile(id,'project-tile')).join('');
if($('[data-project-catalog]'))$('[data-project-catalog]').innerHTML=projectOrder.map(id=>projectTile(id,'catalog-project')).join('');

// Homepage discipline interaction.
const disciplineData={build:{src:'media/cases/slotting-main.webp',label:'APPLICATION / CUSTOM MACHINE',title:'Four-servo slotting architecture',href:'machines.html?type=spm'},restore:{src:'media/retrofit/kellenberg.webp',label:'RETROFIT / MACHINE TOOL',title:'Kellenberg CNC grinding modernization',href:'machines.html?type=retrofit'},manufacture:{src:'media/solutions/precision.webp',label:'PROCESS / PRECISION',title:'Machine-tool knowledge applied to manufacturing',href:'index.html#systems'}};
$$('[data-discipline]').forEach(btn=>btn.addEventListener('mouseenter',()=>setDiscipline(btn.dataset.discipline)));$$('[data-discipline]').forEach(btn=>btn.addEventListener('focus',()=>setDiscipline(btn.dataset.discipline)));function setDiscipline(key){const d=disciplineData[key];if(!d)return;$$('[data-discipline]').forEach(b=>b.classList.toggle('is-active',b.dataset.discipline===key));const im=$('[data-discipline-image]');if(im&&im.src.indexOf(d.src)<0){im.style.opacity=.25;setTimeout(()=>{im.src=d.src;im.style.opacity=1},130)}$('[data-discipline-label]')&&($('[data-discipline-label]').textContent=d.label);$('[data-discipline-title]')&&($('[data-discipline-title]').textContent=d.title);const a=$('.discipline-preview a');if(a)a.href=d.href;}

// Homepage system index.
const systemData={
mechanical:{src:'media/legacy/spindle-interface.webp',k:'MACHINE / WORKHOLDING',t:'Mechanical architecture around the process',p:'Machine structure, spindle, workholding and fixture decisions are treated as one production system.',tags:['Machine architecture','Workholding','Fixtures']},
controls:{src:'media/retrofit/jig-grinding.webp',k:'CNC / PLC / HMI',t:'Controls integrated to real machine behaviour',p:'CNC, PLC, HMI and servo systems are selected around motion, sequencing, interlocks and operator use.',tags:['CNC','PLC / HMI','Servo']},
fluid:{src:'media/cases/air-leak-detail.webp',k:'HYDRAULIC / PNEUMATIC',t:'Fluid power engineered into the application',p:'Hydraulic and pneumatic systems support clamping, movement, testing and process control where the machine requires them.',tags:['Hydraulics','Pneumatics','Testing']},
electrical:{src:'media/cases/jig-main.webp',k:'ELECTRICAL / RETROFIT',t:'Electrical systems built around maintainable machine function',p:'Panels, wiring, drives, controls and field devices are integrated back to machine performance and serviceability.',tags:['Control panels','Field wiring','Drives']},
automation:{src:'media/legacy/centerless-conveyor.webp',k:'AUTOMATION / HANDLING',t:'Production flow beyond the cutting operation',p:'Feeding, unloading, indexing, conveyors and inspection are engineered as part of the wider production cell.',tags:['Feeding','Conveyors','Handling']},
precision:{src:'media/legacy/wheel-balancing-unit.webp',k:'PRECISION / PROCESS',t:'Machine-tool knowledge closes the engineering loop',p:'Turning, machining and grinding knowledge connects machine condition, workholding, measurement and component requirements.',tags:['Grinding','Alignment','Process']}
};
$$('[data-system]').forEach(btn=>{const fn=()=>setSystem(btn.dataset.system);btn.addEventListener('mouseenter',fn);btn.addEventListener('focus',fn)});function setSystem(key){const d=systemData[key];if(!d)return;$$('[data-system]').forEach(b=>b.classList.toggle('is-active',b.dataset.system===key));const im=$('[data-system-image]');if(im){im.style.opacity=.15;setTimeout(()=>{im.src=d.src;im.alt=d.t;im.style.opacity=1},110)}$('[data-system-kicker]')&&($('[data-system-kicker]').textContent=d.k);$('[data-system-title]')&&($('[data-system-title]').textContent=d.t);$('[data-system-copy]')&&($('[data-system-copy]').textContent=d.p);const tags=$('[data-system-tags]');if(tags)tags.innerHTML=(d.tags||[]).map(x=>`<span>${x}</span>`).join('');}

// Process progression.
if('IntersectionObserver'in window){const sio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');sio.unobserve(e.target)}}),{threshold:.3});const steps=$$('[data-process-step]'),bar=$('[data-process-progress]');if(steps.length){const pio=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){const i=steps.indexOf(e.target);steps.forEach((s,j)=>s.classList.toggle('is-active',j<=i));if(bar)bar.style.width=`${((i+1)/steps.length)*100}%`;}})},{rootMargin:'-30% 0px -50%',threshold:.15});steps.forEach(s=>pio.observe(s));}}

// Lazy machine video only when close to viewport.
$$('[data-lazy-video]').forEach(v=>{if(reduce)return;const vio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){v.querySelectorAll('source[data-src]').forEach(s=>s.src=s.dataset.src);v.load();v.play().catch(()=>{});vio.unobserve(v)}}),{rootMargin:'250px'});vio.observe(v)});

// Home archive preview.
if($('[data-archive-preview]')){const ids=['spm07','spm12','spm20','spm09','rtf09','rtf11'];const box=$('[data-archive-preview]');box.innerHTML=ids.map(id=>{const m=machineArchive.find(x=>x.id===id);return `<button class="archive-preview-row" type="button" data-machine-open="${id}" data-archive-hover="${id}"><span>${idxLabel(m)}</span><strong>${m.title}</strong><small>${m.customer||m.control||cat[m.category]}</small><i>→</i></button>`}).join('');const show=m=>{if(!m)return;const frame=$('[data-archive-home-frame]');if(frame)frame.innerHTML=m.media?.length?`<img src="${m.media[0]}" alt="${m.title}" />`:placeholder(idxLabel(m));$('[data-archive-home-id]')&&($('[data-archive-home-id]').textContent=idxLabel(m));$('[data-archive-home-title]')&&($('[data-archive-home-title]').textContent=m.title);$('[data-archive-home-note]')&&($('[data-archive-home-note]').textContent=m.note);$$('[data-archive-hover]').forEach(r=>r.classList.toggle('is-active',r.dataset.archiveHover===m.id));};$$('[data-archive-hover]').forEach(r=>{const m=machineArchive.find(x=>x.id===r.dataset.archiveHover);r.addEventListener('mouseenter',()=>show(m));r.addEventListener('focus',()=>show(m));});show(machineArchive.find(x=>x.id===ids[0]));}

// Engineering Archive page.
let state={type:'all',category:'all',control:'all',query:'',media:false,view:'visual'};let currentMatches=[...machineArchive];
const visual=$('[data-archive-visual]'),indexWrap=$('[data-archive-index]'),indexList=$('[data-index-list]');
const controlMatch=(m,k)=>{if(k==='all')return true;const t=searchText(m);if(k==='plc')return /plc|hmi/.test(t);if(k==='servo')return /servo/.test(t);if(k==='vfd')return /vfd/.test(t);return t.includes(k)};
const matches=()=>machineArchive.filter(m=>(state.type==='all'||m.type===state.type)&&(state.category==='all'||m.category===state.category)&&controlMatch(m,state.control)&&(!state.media||m.media?.length)&&(!state.query||searchText(m).includes(state.query)));
const archiveCard=m=>`<button class="archive-card" type="button" data-machine-open="${m.id}"><figure>${m.media?.length?`<img src="${m.media[0]}" alt="${m.title}" loading="lazy" />`:placeholder(idxLabel(m))}</figure><div class="archive-card-body"><div class="archive-card-id"><span>${idxLabel(m)}</span><small>${archiveTypeName[m.type]}</small></div><h3>${m.title}</h3><p>${m.note}</p><footer><span>${m.customer||m.control||cat[m.category]}</span><i>Open dossier ↗</i></footer></div></button>`;
const indexRow=m=>`<button class="index-row" type="button" data-index-id="${m.id}" data-machine-open="${m.id}"><span>${idxLabel(m)}</span><strong>${m.title}</strong><small>${m.customer||m.control||cat[m.category]}</small><i>→</i></button>`;
function renderArchive(){if(!visual)return;currentMatches=matches();visual.innerHTML=currentMatches.map(archiveCard).join('')||'<p>No matching reference. Try another filter.</p>';indexList.innerHTML=currentMatches.map(indexRow).join('')||'<p>No matching reference.</p>';$('[data-results-count]').textContent=`${currentMatches.length} reference${currentMatches.length===1?'':'s'}`;$('[data-results-summary]').textContent=`${currentMatches.filter(m=>m.type==='spm').length} custom / SPM · ${currentMatches.filter(m=>m.type==='retrofit').length} retrofit · ${currentMatches.filter(m=>m.media?.length).length} photo documented`;wireOpeners();wireIndexHover();}
function updateButtons(){$$('[data-type-filter]').forEach(b=>{const on=b.dataset.typeFilter===state.type;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',String(on))});$$('[data-category]').forEach(b=>b.classList.toggle('is-active',b.dataset.category===state.category));$$('[data-control]').forEach(b=>b.classList.toggle('is-active',b.dataset.control===state.control));const mb=$('[data-media-filter]');if(mb){mb.classList.toggle('is-active',state.media);mb.setAttribute('aria-pressed',String(state.media))}}
$$('[data-type-filter]').forEach(b=>b.addEventListener('click',()=>{state.type=b.dataset.typeFilter;updateButtons();renderArchive()}));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;updateButtons();renderArchive()}));$$('[data-control]').forEach(b=>b.addEventListener('click',()=>{state.control=b.dataset.control;updateButtons();renderArchive()}));$('[data-media-filter]')?.addEventListener('click',()=>{state.media=!state.media;updateButtons();renderArchive()});$('[data-archive-search]')?.addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderArchive()});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('is-active',x===b));visual.hidden=state.view!=='visual';indexWrap.hidden=state.view!=='index';if(state.view==='index'&&currentMatches[0])showIndexPreview(currentMatches[0]);}));
function showIndexPreview(m){if(!m)return;$$('[data-index-id]').forEach(r=>r.classList.toggle('is-active',r.dataset.indexId===m.id));const media=$('[data-index-preview-media]');media.innerHTML=m.media?.length?`<img src="${m.media[0]}" alt="${m.title}" />`:placeholder(idxLabel(m));$('[data-index-preview-id]').textContent=idxLabel(m);$('[data-index-preview-title]').textContent=m.title;$('[data-index-preview-note]').textContent=m.note;}
function wireIndexHover(){$$('[data-index-id]').forEach(r=>{const m=machineArchive.find(x=>x.id===r.dataset.indexId);r.addEventListener('mouseenter',()=>showIndexPreview(m));r.addEventListener('focus',()=>showIndexPreview(m));})}
if(page==='machines'){const params=new URLSearchParams(location.search);if(params.get('type'))state.type=params.get('type');if(params.get('q')){state.query=params.get('q').toLowerCase();$('[data-archive-search]').value=params.get('q')}updateButtons();renderArchive();}

// Dossier system with previous / next, keyboard arrows and focus management.
const dossier=$('[data-dossier]');let activeId='',activeMode='feature',activeList=[];let lastFocus=null;
function mediaHtml(d,id){if(d.media?.length){const figs=d.media.map((src,i)=>`<figure><img src="${src}" alt="${d.title} — project view ${i+1}" /></figure>`).join('');const vid=d.video?`<figure><video controls muted playsinline preload="metadata"><source src="${d.video}" type="video/webm"></video></figure>`:'';return figs+vid;}return placeholder(id||'ARCHIVE');}
function normalizeMachine(m){if(m.featureId&&featureData[m.featureId])return {...featureData[m.featureId],archiveId:m.id,id:m.featureId,displayId:idxLabel(m),archive:m};return {...m,id:m.id,displayId:idxLabel(m),summary:m.note,facts:[['Archive type',archiveTypeName[m.type]],['Application',cat[m.category]],m.customer?['Customer reference',m.customer]:m.control?['Control / system',m.control]:['Source','VSK machine archive']],sections:[['Archive reference','Source description',m.note],['Information policy','What is shown','Only information supported by the supplied VSK source material is shown. Additional project specifications can be added when VSK confirms them.']]};}
function normalizeFeature(id){const d=featureData[id];return d?{...d,id,displayId:d.index||'DOCUMENTED PROJECT'}:null;}
function fillDossier(d){$('[data-dossier-kicker]').textContent=d.type||'ENGINEERING REFERENCE';$('[data-dossier-id]').textContent=d.displayId||d.index||'';$('[data-dossier-title]').textContent=d.title;$('[data-dossier-summary]').textContent=d.summary||d.note||'';$('[data-dossier-media]').innerHTML=mediaHtml(d,d.displayId);const facts=d.facts||[];$('[data-dossier-facts]').innerHTML=facts.map(([k,v])=>`<div class="dossier-fact"><span>${k}</span><strong>${v}</strong></div>`).join('');const sections=d.sections||[];$('[data-dossier-sections]').innerHTML=sections.map(s=>{const [label,a,b]=s;return b!==undefined?`<section class="dossier-section"><span>${label}</span><div><h3>${a}</h3><p>${b}</p></div></section>`:`<section class="dossier-section"><span>${label}</span><div><p>${a}</p></div></section>`}).join('');const i=activeList.indexOf(activeId);$('[data-dossier-position]').textContent=i>=0?`${String(i+1).padStart(2,'0')} / ${String(activeList.length).padStart(2,'0')}`:'';$('[data-dossier-media]').scrollTop=0;$('.dossier-panel').scrollTop=0;}
function openDossier(id,mode='feature'){lastFocus=document.activeElement;activeMode=mode;if(mode==='machine'){const m=machineArchive.find(x=>x.id===id);if(!m)return;activeId=id;activeList=(page==='machines'?currentMatches:machineArchive).map(x=>x.id);fillDossier(normalizeMachine(m));}else{if(!featureData[id])return;activeId=id;activeList=projectOrder.filter(x=>featureData[x]);fillDossier(normalizeFeature(id));}dossier.hidden=false;dossier.setAttribute('aria-hidden','false');document.body.classList.add('is-locked');setTimeout(()=>$('.dossier-panel')?.focus(),0);}
function closeDossier(){dossier.hidden=true;dossier.setAttribute('aria-hidden','true');document.body.classList.remove('is-locked');lastFocus?.focus?.()}
function stepDossier(dir){if(!activeList.length)return;let i=activeList.indexOf(activeId);i=(i+dir+activeList.length)%activeList.length;openDossier(activeList[i],activeMode);}
function wireOpeners(){$$('[data-machine-open]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openDossier(b.dataset.machineOpen,'machine'))});$$('[data-feature-open]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>openDossier(b.dataset.featureOpen,'feature'))});}
wireOpeners();$$('[data-dossier-close]').forEach(b=>b.addEventListener('click',closeDossier));$$('[data-dossier-next]').forEach(b=>b.addEventListener('click',()=>stepDossier(1)));$('[data-dossier-prev]')?.addEventListener('click',()=>stepDossier(-1));

// Quote flow + file drop.
const quote=$('[data-quote-panel]'),form=$('[data-quote-form]');let quoteStep=1,quoteType='',quoteFile=null,quoteText='';
function setQuoteStep(n){quoteStep=Math.max(1,Math.min(4,n));$$('[data-step]',quote).forEach(s=>s.classList.toggle('is-active',Number(s.dataset.step)===quoteStep));$$('.step-dots i',quote).forEach((d,i)=>d.classList.toggle('is-active',i<quoteStep));$('[data-quote-count]').textContent=`0${quoteStep} / 04`;}
function openQuote(){quote.hidden=false;quote.setAttribute('aria-hidden','false');document.body.classList.add('is-locked');$('[data-quote-success]').hidden=true;form.hidden=false;setQuoteStep(1);setTimeout(()=>$('.quote-shell')?.focus(),0)}function closeQuote(){quote.hidden=true;quote.setAttribute('aria-hidden','true');document.body.classList.remove('is-locked')}
$$('[data-quote-open]').forEach(b=>b.addEventListener('click',openQuote));$$('[data-quote-close]').forEach(b=>b.addEventListener('click',closeQuote));$$('[data-type]',quote).forEach(b=>b.addEventListener('click',()=>{quoteType=b.dataset.type;setQuoteStep(2)}));$$('[data-quote-next]',quote).forEach(b=>b.addEventListener('click',()=>{if(quoteStep===2&&String(form.elements.requirement.value||'').trim().length<12){form.elements.requirement.focus();return}setQuoteStep(quoteStep+1)}));$$('[data-quote-prev]',quote).forEach(b=>b.addEventListener('click',()=>setQuoteStep(quoteStep-1)));
const fileInput=$('[data-quote-file]'),drop=$('[data-file-drop]');function setFile(f){quoteFile=f||null;$('[data-file-text]').textContent=f?f.name:'No file selected'}fileInput?.addEventListener('change',e=>setFile(e.target.files?.[0]));['dragenter','dragover'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('is-dragging')}));['dragleave','drop'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('is-dragging')}));drop?.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(f)setFile(f)});drop?.addEventListener('click',()=>fileInput?.click());
form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),name=String(fd.get('name')||'').trim(),email=String(fd.get('email')||'').trim(),phone=String(fd.get('phone')||'').replace(/\D/g,''),msg=String(fd.get('requirement')||'').trim(),company=String(fd.get('company')||'').trim();let err='';if(!name)err='Please enter your name.';else if(!/^\S+@\S+\.\S+$/.test(email))err='Please enter a valid email address.';else if(phone.length!==10)err='Please enter a 10-digit phone number.';$('[data-form-error]').textContent=err;if(err)return;quoteText=`Requirement type: ${quoteType||'General'}\nName: ${name}\nCompany: ${company}\nEmail: ${email}\nPhone: ${phone}\nDrawing/spec selected: ${quoteFile?.name||'None selected'}\n\nRequirement:\n${msg}`;const mail=`mailto:vsk.electromech@gmail.com?subject=${encodeURIComponent(`VSK Engineering Requirement — ${quoteType||'General'}`)}&body=${encodeURIComponent(quoteText+'\n\nPreview note: please attach the selected local file manually.')}`;$('[data-mail-link]').href=mail;form.querySelectorAll('.quote-step').forEach(s=>s.classList.remove('is-active'));$('[data-quote-success]').hidden=false;});$('[data-copy-enquiry]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(quoteText);$('[data-copy-enquiry]').textContent='Copied ✓'}catch{}});

// Basic focus trap for open dialogs.
function trap(e,root){if(e.key!=='Tab')return;const f=$$('button,a,input,textarea,[tabindex]:not([tabindex="-1"])',root).filter(x=>!x.disabled&&!x.hidden);if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
document.addEventListener('keydown',e=>{if(!dossier?.hidden){if(e.key==='Escape')closeDossier();else if(e.key==='ArrowRight')stepDossier(1);else if(e.key==='ArrowLeft')stepDossier(-1);else trap(e,dossier);return}if(!quote?.hidden){if(e.key==='Escape')closeQuote();else trap(e,quote);return}if(e.key==='Escape'&&nav?.classList.contains('is-open')){nav.classList.remove('is-open');document.body.classList.remove('nav-open');menu?.setAttribute('aria-expanded','false')}});
})();
