const machineArchive=[
    {id:'spm01',type:'spm',category:'handling',title:'Food Grade Conveyor for Cashew Industry',customer:'Shiva Industry',note:'Food-grade conveyor reference for cashew-industry handling.'},
    {id:'spm02',type:'spm',category:'handling',title:'Conveyors for Centerless Grinding Machines',customer:'Rollon Hydraulics / Transtech Gears',note:'Conveyor reference for centerless-grinding machine applications.',media:['media/legacy/centerless-conveyor.webp']},
    {id:'spm03',type:'spm',category:'turning',title:'Motor Spigot CNC Turning Machine',customer:'Transtech Gears India',note:'CNC turning machine reference for motor-spigot production.'},
    {id:'spm04',type:'spm',category:'turning',title:'Motor Flange Facing Machine',customer:'Transtech Gears India',note:'Facing-machine reference for motor-flange production.'},
    {id:'spm05',type:'spm',category:'pressing',title:'Hydraulic Bearing Pressing Machine for Rotor Shaft',customer:'Transtech Gears India',note:'Hydraulic pressing machine reference for bearing-to-rotor-shaft assembly.'},
    {id:'spm06',type:'spm',category:'pressing',title:'Hand Pressing Machine for Bearing Pressing',customer:'Transtech Gears India',note:'Manual pressing-machine reference for bearing assembly.'},
    {id:'spm07',type:'spm',category:'turning',title:'Vertical Turning CNC Lathe for PTFE Rod',customer:'Trelleborg Sealing',note:'Vertical CNC turning reference for 900 mm PTFE rod.',media:['media/projects/vertical-turning.webp','media/solutions/vertical-turning.webp'],featureId:'vertical'},
    {id:'spm08',type:'spm',category:'turning',title:'Horizontal PLC & Servo Controlled 2-Axis Lathe',customer:'Trelleborg',note:'Two-axis lathe reference using PLC and servo control.'},
    {id:'spm09',type:'spm',category:'turning',title:'Vertical Rod Boring Machine with 350 mm 6-Jaw Chuck',note:'Vertical rod-boring machine reference.',media:['media/projects/rod-boring.webp','media/legacy/rod-boring-cnc.webp'],featureId:'rod'},
    {id:'spm10',type:'spm',category:'cutting',title:'Rod Splitting SPM Machine',note:'Special-purpose rod-splitting machine reference.'},
    {id:'spm11',type:'spm',category:'cutting',title:'2-Axis Servo Notching Machine',note:'Two-axis servo notching machine reference.',media:['media/projects/slotting.webp']},
    {id:'spm12',type:'spm',category:'cutting',title:'4-Axis Servo Notching Machine',note:'Four-axis servo notching machine reference.',media:['media/cases/slotting-main.webp','media/cases/slotting-detail.webp'],featureId:'slotting'},
    {id:'spm13',type:'spm',category:'cutting',title:'4-Axis Servo Notching — Top & Bottom Simultaneous',note:'Four-axis notching reference for simultaneous top and bottom operations.',media:['media/cases/slotting-main.webp','media/cases/slotting-detail.webp'],featureId:'slotting'},
    {id:'spm14',type:'spm',category:'handling',title:'4-Axis Servo Notching with Auto Loading & Stacker',note:'Servo notching reference with automated loading and stacker system.',media:['media/projects/slotting.webp','media/cases/slotting-detail.webp'],featureId:'slotting'},
    {id:'spm15',type:'spm',category:'pressing',title:'2-Axis Bottom Notching + O-Ring Assembly + Vision Inspection',note:'Integrated notching, assembly and vision-inspection machine reference.'},
    {id:'spm16',type:'spm',category:'cutting',title:'Razor Cross-Cutting Machine for Backup Rings',note:'Cross-cutting machine reference for backup rings.'},
    {id:'spm17',type:'spm',category:'cutting',title:'Seal Cross-Cutting Machine with Auto Loading',note:'Seal cross-cutting machine reference with automatic loading.'},
    {id:'spm18',type:'spm',category:'cutting',title:'Ring Cutting Machine — 50 to 200 mm with Auto Loading',note:'Ring-cutting reference covering 50–200 mm sizes with automatic loading.'},
    {id:'spm19',type:'spm',category:'cutting',title:'Bush Cross-Cutting Machine with Auto Loading',note:'Bush cross-cutting machine reference with automatic loading.'},
    {id:'spm20',type:'spm',category:'testing',title:'Air Leakage Testing Machine with Festo Servo Unit',note:'Air-leak testing machine reference using a Festo servo unit.',media:['media/projects/air-leak.webp','media/cases/air-leak-main.webp','media/cases/air-leak-detail.webp'],featureId:'airleak'},
    {id:'spm21',type:'spm',category:'finishing',title:'Aluminium Component Deburring Machine',note:'Deburring-machine reference for aluminium components.'},
    {id:'spm22',type:'spm',category:'handling',title:'Ring Drilling & Chamfering with Auto Pickup / Unloading',note:'Ring drilling and chamfering reference with automated pickup and unloading.'},
    {id:'spm23',type:'spm',category:'pressing',title:'Greasing Machine for Seals',note:'Seal greasing machine reference.'},
    {id:'spm24',type:'spm',category:'finishing',title:'Seal Scrubbing & Adhesive Spraying Machine',note:'Seal surface-preparation and adhesive-spraying reference.'},
    {id:'spm25',type:'spm',category:'finishing',title:'Seal Scrubbing & Polishing with Auto Indexing',note:'Seal scrubbing and polishing reference with automatic indexing.'},
    {id:'spm26',type:'spm',category:'finishing',title:'Internal Seal Scrubbing & Spraying Machine',note:'Internal seal scrubbing and spraying machine reference.'},
    {id:'spm27',type:'spm',category:'finishing',title:'Epoxy Painting Machine for Seals',note:'Epoxy-painting machine reference for seals.'},
    {id:'spm28',type:'spm',category:'finishing',title:'Manual Seal Painting, Adhesive Dipping & Drying Machine',note:'Manual painting, adhesive dipping and drying equipment reference.'},
    {id:'spm29',type:'spm',category:'cutting',title:'Rubber Bush Cutting Machine — 30 to 50 mm',note:'Rubber-bush cutting reference covering 30–50 mm.'},
    {id:'spm30',type:'spm',category:'pressing',title:'Seal Pressing Machine',note:'Seal pressing machine reference.'},
    {id:'spm31',type:'spm',category:'cutting',title:'Spiral Mandrel Cutting Machine',note:'Spiral mandrel cutting machine reference.'},
    {id:'spm32',type:'spm',category:'finishing',title:'Thread Deburring Machine',note:'Thread deburring machine reference.'},
    {id:'spm33',type:'spm',category:'finishing',title:'Spinning Machine for Metal Seals',note:'Metal-seal spinning machine reference.'},
    {id:'spm34',type:'spm',category:'turning',title:'Vertical Type Seal Facing Machine',note:'Vertical seal-facing machine reference.',media:['media/legacy/metal-facing-machine.webp'],featureId:'facing'},
    {id:'spm35',type:'spm',category:'finishing',title:'Paint Agitating Machine',customer:'Prestige',note:'Paint-agitating machine reference.',media:['media/projects/paint-agitating.webp','media/legacy/paint-agitating-machine.webp'],featureId:'paint'},
    {id:'spm36',type:'spm',category:'controls',title:'Gehring Maske Honing Machine Control Panel — Manufacture & Supply',note:'Control-panel manufacturing and supply reference for a honing machine.'},
    {id:'spm37',type:'spm',category:'controls',title:'Hydraulic & Pneumatic Design and Manufacturing',note:'Hydraulic and pneumatic engineering / manufacturing reference.'},
    {id:'spm38',type:'spm',category:'handling',title:'2 m Conveyor Rod Milling Machine — up to 60 mm',customer:'Sapthagiri Enterprises, Salem',note:'Two-metre conveyor rod-milling machine reference for rods up to 60 mm.'},
    {id:'spm39',type:'spm',category:'turning',title:'2 m × 200 mm Pipe Boring Machine — Twin Spindle',customer:'Sapthagiri Enterprises, Salem',note:'Two-metre, 200 mm diameter conveyor pipe-boring reference with two spindles.'},

    {id:'rtf01',type:'retrofit',category:'grinding',title:'Studer OD CNC Grinding — Fanuc 0i-TF',control:'Fanuc 0i-TF',note:'OD CNC grinding reconditioning / control retrofit reference.'},
    {id:'rtf02',type:'retrofit',category:'grinding',title:'Mitsubishi Grinding Machine — Fanuc 0i-TF',control:'Fanuc 0i-TF',note:'Grinding-machine reconditioning / Fanuc retrofit reference.'},
    {id:'rtf03',type:'retrofit',category:'grinding',title:'Toyoda Grinding Machine — Fanuc 0i-TF Plus',control:'Fanuc 0i-TF Plus',note:'Grinding-machine reconditioning / control retrofit reference.'},
    {id:'rtf04',type:'retrofit',category:'grinding',title:'Koyo Internal Grinding — Fanuc 0i-TF Plus',control:'Fanuc 0i-TF Plus',note:'Internal-grinding reconditioning / control retrofit reference.'},
    {id:'rtf05',type:'retrofit',category:'controls',title:'HMC — Fagor Control with 60-Tool Magazine',control:'Fagor',note:'Horizontal machining-centre reconditioning reference with a 60-tool magazine.'},
    {id:'rtf06',type:'retrofit',category:'controls',title:'HMT VMC Machine',note:'HMT vertical machining-centre reconditioning reference.'},
    {id:'rtf07',type:'retrofit',category:'turning',title:'HMT Turning Centre',note:'HMT turning-centre reconditioning reference.'},
    {id:'rtf08',type:'retrofit',category:'turning',title:'Sands Flat Bed Turning Lathe — Fanuc CNC',control:'Fanuc CNC',note:'Flat-bed turning-lathe retrofit reference.'},
    {id:'rtf09',type:'retrofit',category:'grinding',title:'Hauser 5-Axis Jig Grinding — PLC / HMI + 3 Servo Axes',control:'PLC / HMI / Servo',note:'Five-axis jig-grinding retrofit reference with PLC, HMI and servo motors on three axes.',media:['media/retrofit/jig-grinding.webp','media/cases/jig-main.webp','media/cases/jig-detail.webp'],featureId:'jig'},
    {id:'rtf10',type:'retrofit',category:'grinding',title:'Jung Berlin CNC Grinding — Fanuc 0i-TF Plus',control:'Fanuc 0i-TF Plus',note:'CNC grinding reconditioning / control retrofit reference.'},
    {id:'rtf11',type:'retrofit',category:'grinding',title:'Kellenberg CNC Grinding — Fanuc 0i-TF Plus',control:'Fanuc 0i-TF Plus',note:'CNC grinding reconditioning / control retrofit reference.',media:['media/retrofit/kellenberg.webp','media/motion/kellenberg-still.webp'],featureId:'kellenberg'},
    {id:'rtf12',type:'retrofit',category:'grinding',title:'Voumard CNC Internal Grinding — Fanuc 0i-TF Plus',control:'Fanuc 0i-TF Plus',note:'Internal-grinding reconditioning / control retrofit reference.'},
    {id:'rtf13',type:'retrofit',category:'controls',title:'4-Axis Vertical Honing — PLC / HMI Retrofit',control:'PLC / HMI',note:'Four-axis vertical honing machine retrofit reference.'},
    {id:'rtf14',type:'retrofit',category:'controls',title:'Hardinge Machine — Mechanical Retrofitting',note:'Mechanical retrofitting reference for a Hardinge machine.'},
    {id:'rtf15',type:'retrofit',category:'turning',title:'Hyundai CNC Turning Machine',note:'CNC turning-machine reconditioning reference.'}
  ];

const featureData={
    zcut:{title:'Z-Cut Machine',type:'Special Purpose Machine',index:'ENGINEERING CASE',summary:'A dedicated Z-cut production machine with a recorded 0.02 mm application tolerance reference.',media:['media/legacy/z-cut-machine.webp','media/projects/z-cut.webp'],facts:[['Tolerance','0.02 mm reference'],['Scope','Custom machine engineering'],['Application','Z-cut / punching']],sections:[['Application','Tercite punching / Z-cut application with a recorded 0.02 mm tolerance requirement.'],['Engineering approach','Mechanical architecture, workholding / tooling interface and controlled machine sequence are presented as one production solution.']]},
    slotting:{title:'Four-Servo Seal Slotting / Notching',type:'Servo Special Purpose Machine',index:'CUSTOM MACHINE',summary:'A multi-servo special-purpose machine family for seal slotting and notching operations.',media:['media/cases/slotting-main.webp','media/cases/slotting-detail.webp','media/projects/slotting.webp'],facts:[['Motion','4-axis servo reference'],['Automation','Auto-loading variant recorded'],['Application','Seal notching / slotting']],sections:[['Machine family','VSK references include 2-axis and 4-axis servo notching, simultaneous top/bottom notching and an auto-loading stacker variant.'],['System integration','The project demonstrates mechanical architecture and servo/control integration around a customer-specific operation.']]},
    airleak:{title:'Air Leakage Testing Machine',type:'Testing & Inspection Equipment',index:'CUSTOM MACHINE',summary:'Dedicated air-leak testing equipment combining the test fixture, pneumatic system and controlled machine sequence.',media:['media/cases/air-leak-main.webp','media/cases/air-leak-detail.webp'],facts:[['Motion','Festo servo unit'],['Application','Air leakage testing'],['Scope','Fixture + pneumatic + control']],sections:[['Testing system','Air leakage testing equipment integrated with a Festo servo unit, fixture and machine sequence.'],['System detail','Machine and fixture views show how the testing arrangement, pneumatics and structure work together.']]},
    rod:{title:'Rod Boring CNC Machine',type:'CNC Application',index:'ENGINEERING CASE',summary:'CNC pre-boring application for PTFE tubes using a Siemens 802D two-axis control platform.',media:['media/projects/rod-boring.webp','media/legacy/rod-boring-cnc.webp'],facts:[['Control','Siemens 802D · 2 axis'],['Spindle','5 HP · VFD controlled'],['Workholding','250 mm chuck']],sections:[['Application','PTFE tube pre-boring with a recorded ±0.1 mm application tolerance reference.'],['Machine design','The documented design uses a cast bed, Siemens 802D two-axis CNC, VFD-controlled spindle and 250 mm chuck.']]},
    vertical:{title:'Vertical Turning CNC Lathe',type:'Turning / CNC Application',index:'CUSTOM MACHINE',summary:'Vertical CNC turning machine reference for PTFE rod processing.',media:['media/projects/vertical-turning.webp','media/solutions/vertical-turning.webp'],facts:[['Application','PTFE rod'],['Recorded length','900 mm'],['Type','Vertical CNC turning']],sections:[['Application','Vertical CNC turning for a recorded 900 mm PTFE rod application.'],['Machine view','Project photography shows the machine arrangement and working area.']]},
    paint:{title:'Paint Agitating Machine',type:'Process Equipment',index:'CUSTOM MACHINE',summary:'Compact process-equipment reference for paint agitation.',media:['media/projects/paint-agitating.webp','media/legacy/paint-agitating-machine.webp'],facts:[['Customer','Prestige'],['Type','Paint agitating equipment'],['Category','Process equipment']],sections:[['Application','Paint agitation equipment supplied with Prestige recorded as the customer reference.'],['Engineering scope','The project broadens VSK’s process-equipment experience beyond conventional CNC machine tools.']]},
    jig:{title:'Hauser 5-Axis Jig Grinding Retrofit',type:'Machine Reconditioning & Retrofit',index:'RETROFIT 09 / 15',summary:'Five-axis jig-grinding retrofit reference using PLC, HMI and servo motors on three axes.',media:['media/retrofit/jig-grinding.webp','media/cases/jig-main.webp','media/cases/jig-detail.webp'],facts:[['Platform','Hauser 5-axis jig grinding'],['Control scope','PLC + HMI'],['Motion scope','Servo motors for 3 axes']],sections:[['Retrofit scope','PLC and HMI retrofit work with servo motors applied to three axes.'],['Machine-tool focus','The work focuses on modernizing the existing jig-grinding platform and its control/motion system.']]},
    kellenberg:{title:'Kellenberg CNC Grinding Retrofit',type:'Machine Reconditioning & Retrofit',index:'RETROFIT 11 / 15',summary:'Kellenberg CNC grinding reconditioning reference with a Fanuc 0i-TF Plus control system.',media:['media/retrofit/kellenberg.webp','media/motion/kellenberg-still.webp'],video:'media/motion/kellenberg-loop.webm',facts:[['Machine','Kellenberg CNC grinding'],['Control','Fanuc 0i-TF Plus'],['Category','Reconditioning / retrofit']],sections:[['Retrofit scope','Kellenberg CNC grinding modernization with a Fanuc 0i-TF Plus system.'],['Machine views','Exterior, process-area and motion material show the machine and retrofit context from multiple angles.']]},
    wheel:{title:'Grinding Wheel Balancing / Alignment Unit',type:'Precision Machine-Tool Unit',index:'ENGINEERING CASE',summary:'A project reference for external alignment of a 1000 mm grinding wheel with a 20 micron face-out requirement.',media:['media/legacy/wheel-balancing-unit.webp'],facts:[['Wheel diameter','1000 mm'],['Alignment reference','20 μm face-out'],['Mounting reference','20 μm flatness']],sections:[['Application','External alignment of a 1000 mm grinding wheel with a recorded 20 μm face-out reference.'],['Design','The documented unit uses a fabricated structure and wheel-spindle mounting reference with 20 micron flatness.']]},
    facing:{title:'Metal Facing Machine',type:'Special Purpose Machine',index:'ENGINEERING CASE',summary:'Final-finishing machine for metal oil seals with a recorded 12-second component cycle reference.',media:['media/legacy/metal-facing-machine.webp'],facts:[['Cycle reference','12 seconds'],['Spindle','5 HP'],['Tailstock','MT4 · 180 mm stroke']],sections:[['Application','Final finishing of metal oil seals after the pressing operation.'],['Design','The documented machine uses a cast bed, pneumatic sliding axis, MT4 tailstock with 180 mm stroke and a 5 HP spindle.']]},
    udrill:{title:'U Drill Machine',type:'Special Purpose Machine',index:'ENGINEERING CASE',summary:'Special-purpose U-drill equipment developed for production-focused drilling applications.',media:['media/projects/u-drill.webp'],facts:[['Type','Drilling / special equipment'],['Scope','Special-purpose machine'],['Media','Project photography']],sections:[['Project view','Project photographs show the U-drill machine and its production arrangement.'],['Engineering detail','Technical details can be expanded as additional project specifications are confirmed.']]},
    oven:{title:'Electric Oven',type:'Process Equipment',index:'ENGINEERING CASE',summary:'Industrial electric-oven project for a dedicated production application.',media:['media/motion/electric-oven.webp'],facts:[['Type','Industrial process equipment'],['Application','Dedicated production process'],['Media','Project photography']],sections:[['Project view','Machine photographs show the electric-oven installation and process-equipment layout.'],['Engineering detail','Application and specification details can be expanded as additional project information is confirmed.']]},
    tabletop:{title:'Table Top Lathe',type:'Special Purpose Machine',index:'ENGINEERING CASE',summary:'Servo-controlled table-top lathe developed for PTFE rod pre-turning.',media:['media/legacy/table-top-lathe.webp'],facts:[['Application','PTFE rod pre-turning'],['Recorded length','850 mm'],['Diameter range','12–120 mm']],sections:[['Application','PTFE rod pre-turning with a recorded ±0.1 mm pre-turning diameter tolerance reference.'],['Machine design','The documented machine uses a fabricated bed, servo control, PLC and touch-screen programmed operation.']]},
    conveyor:{title:'Centerless Grinding Conveyor / Feeder',type:'Material Handling / Automation',index:'ENGINEERING CASE',summary:'Conveyor and feeding equipment developed to interface with centerless grinding applications.',media:['media/legacy/centerless-conveyor.webp'],facts:[['Application','Centerless grinding machine feeding'],['Control','PLC interfacing'],['Drive','Geared + VFD motor']],sections:[['Application','Automatic loading and feeding of spool components to centerless grinding machines.'],['Design','The documented conveyor uses a fabricated structure with geared and VFD-controlled drive.']]},
    spindle:{title:'Machine-Tool Spindle / Workholding Interface',type:'Engineering Detail',index:'MACHINE DETAIL',summary:'Close-up machine-tool views highlighting spindle, workholding and interface details.',media:['media/legacy/spindle-closeup.webp','media/legacy/spindle-interface.webp'],facts:[['View','Spindle / workholding detail'],['Context','Machine-tool engineering'],['Focus','Interface & setup']],sections:[['Engineering detail','Close-up views highlight practical spindle, workholding and machine-interface experience.'],['Context','These close-ups are presented as machine-tool engineering details rather than attributed to an unconfirmed customer project.']]}
  };

const categoryNames={turning:'Turning & boring',cutting:'Cutting & notching',handling:'Automation & handling',testing:'Testing & inspection',finishing:'Surface & finishing',pressing:'Pressing & assembly',controls:'Controls & systems',grinding:'Grinding / retrofit'};
const archiveTypeName={spm:'SPM / Custom Machine',retrofit:'Reconditioning / Retrofit'};


const capabilityData={
  mechanical:{index:'01 / MECHANICAL ENGINEERING',title:'Machine architecture, workholding and mechanism design.',copy:'Machine architecture, mechanisms and workholding developed around the component, process and production target.',image:'media/legacy/spindle-interface.webp',alt:'Machine-tool spindle and workholding interface',tags:['MACHINE DESIGN','FIXTURES','WORKHOLDING']},
  controls:{index:'02 / CNC · PLC · HMI',title:'Controls engineered around the machine sequence and production process.',copy:'CNC, PLC, HMI, servo and drive systems integrated to make the complete machine perform as one system.',image:'media/retrofit/jig-grinding.webp',alt:'Jig grinding machine retrofit',tags:['CNC','PLC','HMI']},
  fluid:{index:'03 / HYDRAULICS & PNEUMATICS',title:'Fluid-power systems engineered around clamping, movement, testing and the machine sequence.',copy:'Hydraulic and pneumatic engineering for clamping, testing, actuation and machine functions.',image:'media/cases/air-leak-detail.webp',alt:'Air leak testing fixture and pneumatic system',tags:['PNEUMATICS','FIXTURE','TEST SYSTEM']},
  electrical:{index:'04 / ELECTRICAL SYSTEMS',title:'Electrical systems that connect controls, drives, field devices and machine functions.',copy:'Control panels, field wiring and retrofit integration engineered for dependable machine operation.',image:'media/motion/kellenberg-still.webp',alt:'Kellenberg grinding machine electrical retrofit',tags:['CONTROL PANEL','FIELD WIRING','RETROFIT']},
  automation:{index:'05 / AUTOMATION & HANDLING',title:'Automation built around part flow, repeatability and operator efficiency.',copy:'Conveyors, pick-and-place, indexing, auto loading and machine interfacing for repeatable production.',image:'media/legacy/centerless-conveyor.webp',alt:'Centerless grinding conveyor and handling system',tags:['HANDLING','INTERLOCKS','AUTOMATION']},
  manufacturing:{index:'06 / PRECISION MANUFACTURING',title:'Precision manufacturing supported by practical machine-tool and process knowledge.',copy:'Turning, machining, grinding and finishing supported by practical workholding and process knowledge.',image:'media/legacy/metal-facing-machine.webp',alt:'Metal facing special purpose machine',tags:['MACHINING','FINISHING','PROCESS']}
};

const siteProjects=[
  {id:'kellenberg',code:'RTF / 11',category:'RETROFIT / GRINDING',title:'Kellenberg CNC Grinding Retrofit',cover:'media/retrofit/kellenberg.webp',summary:'Kellenberg grinding-machine modernization with Fanuc 0i-TF Plus.',mediaMode:'photo',position:'center'},
  {id:'rod',code:'SPM / 09',category:'CNC APPLICATION',title:'Rod Boring CNC Machine',cover:'media/projects/rod-boring.webp',summary:'PTFE tube pre-boring using Siemens 802D two-axis control and dedicated workholding.',mediaMode:'photo',position:'center'},
  {id:'zcut',code:'SPM / PRECISION',category:'CUTTING / PRECISION',title:'Z-Cut Machine',cover:'media/projects/z-cut.webp',summary:'Precision cutting application with a recorded 0.02 mm tolerance reference.',mediaMode:'portrait',position:'center'},
  {id:'vertical',code:'SPM / 07',category:'TURNING / CNC',title:'Vertical Turning CNC Lathe',cover:'media/projects/vertical-turning.webp',summary:'Vertical CNC turning reference for PTFE rod processing.',mediaMode:'portrait',position:'center'},
  {id:'jig',code:'RTF / 09',category:'RETROFIT / GRINDING',title:'Hauser Jig Grinding Retrofit',cover:'media/retrofit/jig-grinding.webp',summary:'Five-axis jig-grinding retrofit with PLC, HMI and servo motors on three axes.',mediaMode:'portrait',position:'center'},
  {id:'udrill',code:'SPM / DRILLING',category:'DRILLING / SPM',title:'U Drill Machine',cover:'media/projects/u-drill.webp',summary:'Special-purpose drilling equipment developed for production-focused machining applications.',mediaMode:'photo',position:'center'},
  {id:'slotting',code:'SPM / 12',category:'SERVO SPM',title:'Four-Servo Slotting / Notching',cover:'media/cases/slotting-main.webp',summary:'Multi-servo special-purpose machine family for seal slotting and notching operations.',mediaMode:'technical',position:'center'},
  {id:'airleak',code:'SPM / 20',category:'TESTING / AUTOMATION',title:'Air Leakage Testing Machine',cover:'media/cases/air-leak-main.webp',summary:'Dedicated testing system integrating fixture, pneumatics and controlled machine sequence.',mediaMode:'technical',position:'center'},
  {id:'paint',code:'SPM / 35',category:'PROCESS EQUIPMENT',title:'Paint Agitating Machine',cover:'media/legacy/paint-agitating-machine.webp',summary:'Process-equipment reference supplied for Prestige.',mediaMode:'portrait',position:'center'},
  {id:'oven',code:'PROCESS EQUIPMENT',category:'PROCESS EQUIPMENT',title:'Electric Oven',cover:'media/motion/electric-oven.webp',summary:'Industrial process equipment engineered for a dedicated production application.',mediaMode:'photo',position:'center'}
];

const sampleData={
  vertical:{image:'media/projects/vertical-turning.webp',alt:'Vertical turning CNC machine',label:'SPM / 07 · TURNING',title:'Vertical Turning CNC Lathe'},
  rod:{image:'media/projects/rod-boring.webp',alt:'Rod boring CNC machine',label:'SPM / 09 · BORING',title:'Rod Boring CNC Machine'},
  slotting:{image:'media/cases/slotting-main.webp',alt:'Four-servo slotting machine',label:'SPM / 12 · SERVO SPM',title:'Four-Axis Servo Notching'},
  airleak:{image:'media/cases/air-leak-main.webp',alt:'Air leakage testing machine',label:'SPM / 20 · TESTING',title:'Air Leakage Testing Machine'},
  jig:{image:'media/retrofit/jig-grinding.webp',alt:'Hauser jig grinding retrofit',label:'RTF / 09 · GRINDING',title:'Hauser Jig Grinding Retrofit'},
  kellenberg:{image:'media/retrofit/kellenberg.webp',alt:'Kellenberg grinding machine retrofit',label:'RTF / 11 · GRINDING',title:'Kellenberg CNC Grinding'}
};

const galleryFallback={
  summary:{groups:11,images:24,videos:1},
  groups:[
    {id:'slotting-machine',title:'Four-Servo Seal Slotting / Notching',category:'Special Purpose Machine',items:[
      {type:'image',src:'media/cases/slotting-main.webp',thumb:'media/cases/slotting-main.webp',caption:'Machine overview'},
      {type:'image',src:'media/cases/slotting-detail.webp',thumb:'media/cases/slotting-detail.webp',caption:'Machine detail view'},
      {type:'image',src:'media/projects/slotting.webp',thumb:'media/projects/slotting.webp',caption:'Alternate project view'}]},
    {id:'air-leak-testing',title:'Air Leakage Testing Machine',category:'Testing & Inspection',items:[
      {type:'image',src:'media/cases/air-leak-main.webp',thumb:'media/cases/air-leak-main.webp',caption:'Machine front view'},
      {type:'image',src:'media/cases/air-leak-detail.webp',thumb:'media/cases/air-leak-detail.webp',caption:'Fixture / process section'},
      {type:'image',src:'media/projects/air-leak.webp',thumb:'media/projects/air-leak.webp',caption:'Project documentation view'}]},
    {id:'rod-boring',title:'Rod Boring Machine',category:'CNC / Boring',items:[
      {type:'image',src:'media/projects/rod-boring.webp',thumb:'media/projects/rod-boring.webp',caption:'Machine overview'},
      {type:'image',src:'media/legacy/rod-boring-cnc.webp',thumb:'media/legacy/rod-boring-cnc.webp',caption:'CNC machine reference'}]},
    {id:'vertical-turning',title:'Vertical Turning CNC Machine',category:'CNC Turning',items:[
      {type:'image',src:'media/projects/vertical-turning.webp',thumb:'media/projects/vertical-turning.webp',caption:'Vertical turning machine view'},
      {type:'image',src:'media/solutions/vertical-turning.webp',thumb:'media/solutions/vertical-turning.webp',caption:'Alternate project view'}]},
    {id:'z-cut',title:'Z-Cut Machine',category:'Cutting / Precision',items:[{type:'image',src:'media/projects/z-cut.webp',thumb:'media/projects/z-cut.webp',caption:'Z-Cut project view'}]},
    {id:'u-drill',title:'U Drill Machine',category:'Drilling',items:[{type:'image',src:'media/projects/u-drill.webp',thumb:'media/projects/u-drill.webp',caption:'U-drill machine view'}]},
    {id:'paint-agitating',title:'Paint Agitating Machine',category:'Process Equipment',items:[
      {type:'image',src:'media/projects/paint-agitating.webp',thumb:'media/projects/paint-agitating.webp',caption:'Paint agitating unit'},
      {type:'image',src:'media/legacy/paint-agitating-machine.webp',thumb:'media/legacy/paint-agitating-machine.webp',caption:'Alternate project view'}]},
    {id:'jig-grinding',title:'Hauser Jig Grinding Retrofit',category:'Retrofit / Grinding',items:[
      {type:'image',src:'media/retrofit/jig-grinding.webp',thumb:'media/retrofit/jig-grinding.webp',caption:'Machine overview'},
      {type:'image',src:'media/cases/jig-main.webp',thumb:'media/cases/jig-main.webp',caption:'Retrofit machine view'},
      {type:'image',src:'media/cases/jig-detail.webp',thumb:'media/cases/jig-detail.webp',caption:'Machine detail view'}]},
    {id:'kellenberg',title:'Kellenberg CNC Grinding Retrofit',category:'Retrofit / Grinding',items:[
      {type:'image',src:'media/retrofit/kellenberg.webp',thumb:'media/retrofit/kellenberg.webp',caption:'Machine overview'},
      {type:'image',src:'media/motion/kellenberg-still.webp',thumb:'media/motion/kellenberg-still.webp',caption:'Machine / process view'},
      {type:'video',src_mp4:'media/motion/kellenberg-loop.mp4',src_webm:'media/motion/kellenberg-loop.webm',poster:'media/motion/kellenberg-loop-poster.webp',caption:'Machine motion clip'}]},
     {id:'electric-oven',title:'Electric Oven',category:'Process Equipment',items:[
      {type:'image',src:'media/motion/electric-oven.webp',thumb:'media/motion/electric-oven.webp',caption:'Industrial electric oven'}]},
    {id:'engineering-details',title:'Engineering Detail Archive',category:'Machine-Tool Engineering',items:[
      {type:'image',src:'media/legacy/spindle-closeup.webp',thumb:'media/legacy/spindle-closeup.webp',caption:'Spindle / workholding detail'},
      {type:'image',src:'media/legacy/spindle-interface.webp',thumb:'media/legacy/spindle-interface.webp',caption:'Machine-tool interface detail'},
      {type:'image',src:'media/legacy/wheel-balancing-unit.webp',thumb:'media/legacy/wheel-balancing-unit.webp',caption:'Grinding wheel alignment unit'},
      {type:'image',src:'media/legacy/centerless-conveyor.webp',thumb:'media/legacy/centerless-conveyor.webp',caption:'Centerless grinding conveyor'},
      {type:'image',src:'media/legacy/table-top-lathe.webp',thumb:'media/legacy/table-top-lathe.webp',caption:'Table top lathe'},
      {type:'image',src:'media/legacy/metal-facing-machine.webp',thumb:'media/legacy/metal-facing-machine.webp',caption:'Metal facing machine'},
      {type:'image',src:'media/legacy/enclosed-machine.webp',thumb:'media/legacy/enclosed-machine.webp',caption:'Machine integration detail'}]}
  ]
};
