(()=>{
  const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
  const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;

  if(!$('link[href="styles-v2.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='styles-v2.css';document.head.append(l)}

  const header=$('[data-header]'),progress=$('.scroll-progress span');
  const onScroll=()=>{const y=scrollY;header?.classList.toggle('is-scrolled',y>20);const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max>0?y/max*100:0)+'%';const dna=$('.machine-dna');if(dna&&!reduce){const r=dna.getBoundingClientRect();const p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)));document.documentElement.style.setProperty('--dna-rotate',`${p*72}deg`)}};
  addEventListener('scroll',onScroll,{passive:true});onScroll();
  addEventListener('load',()=>requestAnimationFrame(()=>document.body.classList.add('hero-ready')),{once:true});

  const menuBtn=$('.menu-toggle'),nav=$('#site-nav');
  menuBtn?.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!open));nav?.classList.toggle('is-open',!open)});
  $$('#site-nav a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('is-open');menuBtn?.setAttribute('aria-expanded','false')}));

  const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.14,rootMargin:'0px 0px -4%'});
  $$('[data-reveal], [data-process]').forEach(el=>io.observe(el));

  const counterIO=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(!isIntersecting)return;const end=Number(target.dataset.count);if(reduce){target.textContent=end;counterIO.unobserve(target);return}const start=performance.now(),dur=1200;const tick=t=>{const p=Math.min(1,(t-start)/dur);target.textContent=Math.round(end*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);counterIO.unobserve(target)}),{threshold:.7});
  $$('[data-count]').forEach(el=>counterIO.observe(el));

  const tabs=$$('.solution-tab');
  const activateSolution=id=>{tabs.forEach(t=>{const active=t.dataset.solution===id;t.classList.toggle('is-active',active);t.setAttribute('aria-selected',String(active))});$$('[data-solution-image]').forEach(i=>i.classList.toggle('is-active',i.dataset.solutionImage===id));$$('[data-solution-copy]').forEach(i=>i.classList.toggle('is-active',i.dataset.solutionCopy===id));const map={build:'01',retrofit:'02',manufacture:'03'};const idx=$('[data-solution-index]');if(idx)idx.textContent=map[id]};
  tabs.forEach(t=>t.addEventListener('click',()=>activateSolution(t.dataset.solution)));

  const proof=$('.proof-band');
  if(proof&&!$('.customer-rail')) proof.insertAdjacentHTML('afterend',`<section class="customer-rail" aria-label="Selected customer references"><span>Selected customer references</span><div class="customer-track"><div><strong>Trelleborg Sealing Systems</strong><strong>Yuken India</strong><strong>Transtech Gears India</strong><strong>TMI Rollon Engineering</strong><strong>Sapthagiri Enterprises</strong><strong>Trelleborg Sealing Systems</strong><strong>Yuken India</strong><strong>Transtech Gears India</strong><strong>TMI Rollon Engineering</strong><strong>Sapthagiri Enterprises</strong></div></div></section>`);

  const solutions=$('#solutions');
  if(solutions&&!$('.machine-dna')) solutions.insertAdjacentHTML('afterend',`<section class="section machine-dna" id="dna"><div class="machine-dna__head"><div data-reveal><div class="section-kicker">02 · VSK MACHINE DNA</div><h2>Eight disciplines.<br><span>One machine.</span></h2></div><p data-reveal>A VSK project can move through structure, actuation, controls, electrification and production support without losing the engineering thread between disciplines. The geometry comes directly from the eight-sided VSK mark.</p></div><div class="machine-dna__stage" data-reveal><div class="dna-core"><img src="assets-source/VSK LOGO.png" alt="" /><span>INTEGRATED ENGINEERING</span></div><div class="dna-orbit"><div class="dna-node"><span>01 / MECH</span><strong>Machine Design</strong></div><div class="dna-node"><span>02 / HYD</span><strong>Hydraulics</strong></div><div class="dna-node"><span>03 / PNEU</span><strong>Pneumatics</strong></div><div class="dna-node"><span>04 / CNC</span><strong>CNC Systems</strong></div><div class="dna-node"><span>05 / PLC</span><strong>PLC + HMI</strong></div><div class="dna-node"><span>06 / MOTION</span><strong>Servo + VFD</strong></div><div class="dna-node"><span>07 / ELEC</span><strong>Panels + Wiring</strong></div><div class="dna-node"><span>08 / MAKE</span><strong>Manufacturing</strong></div></div></div></section>`);

  const scroller=$('[data-project-scroller]');
  if(scroller){
    scroller.insertAdjacentHTML('beforebegin',`<div class="project-tools"><div class="project-filters" role="group" aria-label="Filter machine references"><button class="project-filter is-active" data-filter="all">All</button><button class="project-filter" data-filter="spm">SPM</button><button class="project-filter" data-filter="cnc">CNC</button><button class="project-filter" data-filter="automation">Automation</button><button class="project-filter" data-filter="process">Process</button></div><div class="project-count"><span data-project-visible>7</span> selected references</div></div>`);
    const existing=$$('.project-card',scroller);const cats=['spm','automation','cnc','spm'];
    existing.forEach((card,i)=>{card.dataset.category=cats[i]||'spm';card.dataset.tilt='';const img=$('img',card),title=$('h3',card),copy=$('p',card),num=$('.project-number',card);card.dataset.modalTitle=title?.textContent||'VSK machine';card.dataset.modalCopy=copy?.textContent||'';card.dataset.modalImage=img?.getAttribute('src')||'';card.dataset.modalSubtitle=num?.textContent||'Executed machine';card.insertAdjacentHTML('afterbegin','<button class="project-open" type="button" aria-label="Open machine detail">+</button>')});
    scroller.insertAdjacentHTML('beforeend',`<article class="project-card" data-category="cnc" data-tilt data-modal-title="Vertical Turning CNC Machine" data-modal-subtitle="05 / CNC" data-modal-copy="Custom vertical turning machine reference from the VSK archive, representing application-led machine construction and CNC integration." data-modal-image="assets-source/VERTICAL TURNING CNC MACHINE/1520917541365.jpg"><button class="project-open" type="button" aria-label="Open machine detail">+</button><div class="project-image"><img src="assets-source/VERTICAL TURNING CNC MACHINE/1520917541365.jpg" alt="VSK vertical turning CNC machine" loading="lazy" /></div><div class="project-copy"><div class="project-number">05 / CNC</div><h3>Vertical Turning CNC Machine</h3><p>Custom vertical turning machine reference from the VSK project archive.</p><span class="project-chip">CNC integration</span></div></article><article class="project-card" data-category="spm" data-tilt data-modal-title="U-Drill Machine" data-modal-subtitle="06 / SPM" data-modal-copy="Dedicated drilling-machine reference built around a specific production requirement, with machine-side engineering and controls integrated as one scope." data-modal-image="assets-source/U DRILL MACHINE/1520917550194.jpg"><button class="project-open" type="button" aria-label="Open machine detail">+</button><div class="project-image"><img src="assets-source/U DRILL MACHINE/1520917550194.jpg" alt="VSK U drill machine" loading="lazy" /></div><div class="project-copy"><div class="project-number">06 / SPM</div><h3>U-Drill Machine</h3><p>Dedicated drilling equipment engineered for a production-specific operation.</p><span class="project-chip">Custom machine</span></div></article><article class="project-card" data-category="process" data-tilt data-modal-title="Paint Agitating Machine" data-modal-subtitle="07 / PROCESS" data-modal-copy="Custom process equipment from the VSK machine portfolio, demonstrating that the SPM capability extends beyond conventional machining operations." data-modal-image="assets-source/paint aggitating machine/paint aggitating unit.jpg"><button class="project-open" type="button" aria-label="Open machine detail">+</button><div class="project-image"><img src="assets-source/paint aggitating machine/paint aggitating unit.jpg" alt="VSK paint agitating machine" loading="lazy" /></div><div class="project-copy"><div class="project-number">07 / PROCESS</div><h3>Paint Agitating Machine</h3><p>Custom process equipment extending VSK beyond conventional cutting machines.</p><span class="project-chip">Process equipment</span></div></article>`);
    const hint=$('.scroll-hint');
    hint?.insertAdjacentHTML('afterend',`<div class="machine-index"><div class="machine-index__row"><span>TURN / BORE</span><p>Vertical turning CNC lathe · horizontal servo lathe · rod boring · motor spigot turning · motor flange facing · seal facing.</p></div><div class="machine-index__row"><span>CUT / NOTCH</span><p>2-axis and 4-axis servo notching · ring cutting · cross cutting · bush cutting · spiral mandrel cutting · Z-cut punching.</p></div><div class="machine-index__row"><span>TEST / FINISH</span><p>Air-leak testing · deburring · drilling/chamfering · greasing · scrubbing · spraying · polishing · pressing · spinning.</p></div><div class="machine-index__row"><span>HANDLE / MOVE</span><p>Centreless grinding conveyors · auto loading · stacker systems · gantry / pick-and-place interfaces · food-grade conveying.</p></div></div>`);
  }

  if(!$('.project-modal')) document.body.insertAdjacentHTML('beforeend',`<div class="project-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="project-modal-title"><div class="project-modal__backdrop" data-modal-close></div><div class="project-modal__panel"><button class="project-modal__close" type="button" data-modal-close aria-label="Close machine detail">×</button><div class="project-modal__media"><img src="" alt="" data-modal-image /></div><div class="project-modal__copy"><small data-modal-subtitle></small><h3 id="project-modal-title" data-modal-title></h3><p data-modal-copy></p><a href="#contact" class="button button-dark" data-modal-close>Discuss a similar requirement <span>↗</span></a></div></div></div>`);

  const modal=$('.project-modal');let lastFocus=null;
  const closeModal=()=>{if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocus?.focus()};
  const openModal=card=>{if(!modal)return;lastFocus=document.activeElement;$('[data-modal-image]',modal).src=card.dataset.modalImage||'';$('[data-modal-image]',modal).alt=card.dataset.modalTitle||'VSK machine';$('[data-modal-title]',modal).textContent=card.dataset.modalTitle||'';$('[data-modal-subtitle]',modal).textContent=card.dataset.modalSubtitle||'';$('[data-modal-copy]',modal).textContent=card.dataset.modalCopy||'';modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('.project-modal__close',modal)?.focus()};
  $$('.project-open').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();openModal(btn.closest('.project-card'))}));
  $$('[data-modal-close]').forEach(el=>el.addEventListener('click',closeModal));
  addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

  $$('.project-filter').forEach(btn=>btn.addEventListener('click',()=>{const filter=btn.dataset.filter;$$('.project-filter').forEach(b=>b.classList.toggle('is-active',b===btn));let visible=0;$$('.project-card',scroller).forEach(card=>{const show=filter==='all'||card.dataset.category===filter;card.classList.toggle('is-filtered',!show);if(show)visible++});const out=$('[data-project-visible]');if(out)out.textContent=visible;scroller?.scrollTo({left:0,behavior:reduce?'auto':'smooth'})}));

  if(scroller){let down=false,startX=0,startLeft=0;scroller.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;down=true;startX=e.clientX;startLeft=scroller.scrollLeft;scroller.setPointerCapture(e.pointerId);scroller.style.cursor='grabbing'});scroller.addEventListener('pointermove',e=>{if(down)scroller.scrollLeft=startLeft-(e.clientX-startX)});const stop=e=>{down=false;scroller.style.cursor='';try{scroller.releasePointerCapture(e.pointerId)}catch{}};scroller.addEventListener('pointerup',stop);scroller.addEventListener('pointercancel',stop)}

  if(!reduce){
    const parallax=$('[data-parallax]');addEventListener('pointermove',e=>{if(!parallax||innerWidth<900)return;const x=(e.clientX/innerWidth-.5)*14,y=(e.clientY/innerHeight-.5)*10;parallax.style.transform=`translate3d(${x}px,${y}px,0)`},{passive:true});
    $$('.magnetic').forEach(btn=>{btn.addEventListener('pointermove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.12}px)`});btn.addEventListener('pointerleave',()=>btn.style.transform='')});
    $$('.project-card[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<900)return;const r=card.getBoundingClientRect();card.style.setProperty('--tilt-x',`${((e.clientX-r.left)/r.width-.5)*5}deg`);card.style.setProperty('--tilt-y',`${-((e.clientY-r.top)/r.height-.5)*4}deg`);card.style.setProperty('--lift','-4px')});card.addEventListener('pointerleave',()=>{card.style.removeProperty('--tilt-x');card.style.removeProperty('--tilt-y');card.style.removeProperty('--lift')})})
  }

  const navLinks=$$('#site-nav a[href^="#"]').filter(a=>!a.classList.contains('nav-cta'));
  const sectionIO=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-35% 0px -55%',threshold:0});
  navLinks.forEach(a=>{const section=$(a.getAttribute('href'));if(section)sectionIO.observe(section)});

  const scoreSmall=$('.google-score small');if(scoreSmall)scoreSmall.textContent='14 Google reviews · rating shown as a listing snapshot';
  const reviews=$('.reviews-section');if(reviews&&!$('.review-meta-note',reviews)){const link=$('.button-outline-light',reviews);link?.insertAdjacentHTML('beforebegin','<p class="review-meta-note">Google listing currently shows 4.9/5 from 14 reviews. Visit the live listing for the latest rating, review count and customer feedback.</p>')}
  const loc=$('.contact-direct a[href*="google.com/maps"] strong');if(loc)loc.textContent='No. 8, 11th Cross Road · Ganapathy Nagar · Peenya · Bengaluru 560058';

  const schema={"@context":"https://schema.org","@type":"LocalBusiness","name":"VSK Electro-Mech Solutions","description":"Special purpose machines, CNC retrofit and reconditioning, industrial automation and precision engineering in Bengaluru, India.","telephone":"+91 98803 36714","email":"vsk.electromech@gmail.com","foundingDate":"2011","address":{"@type":"PostalAddress","streetAddress":"No. 8, 11th Cross Road, Ganapathy Nagar, Peenya","addressLocality":"Bengaluru","addressRegion":"Karnataka","postalCode":"560058","addressCountry":"IN"},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.9","reviewCount":"14","bestRating":"5"}};
  if(!$('script[data-vsk-schema]')){const s=document.createElement('script');s.type='application/ld+json';s.dataset.vskSchema='';s.textContent=JSON.stringify(schema);document.head.append(s)}

  $$('[data-reveal], .machine-dna [data-reveal]').forEach(el=>{if(!el.classList.contains('is-visible'))io.observe(el)});

  const form=$('[data-enquiry-form]'),status=$('.form-status');
  const formData=()=>Object.fromEntries(new FormData(form).entries());
  const validate=()=>{if(!form.reportValidity())return false;const{phone}=formData();if(!/^\d{10}$/.test(phone)){status.textContent='Please enter a valid 10-digit mobile number.';$('input[name="phone"]')?.focus();return false}status.textContent='';return true};
  const compose=d=>`VSK Engineering Enquiry\n\nName: ${d.name}\nCompany: ${d.company||'-'}\nPhone: ${d.phone}\nEmail: ${d.email}\nRequirement: ${d.requirement}\n\nApplication / Requirement:\n${d.message}`;
  form?.addEventListener('submit',e=>{e.preventDefault();if(!validate())return;const d=formData();location.href=`mailto:vsk.electromech@gmail.com?subject=${encodeURIComponent('Website enquiry — '+d.requirement)}&body=${encodeURIComponent(compose(d))}`});
  $('[data-send="whatsapp"]')?.addEventListener('click',()=>{if(!validate())return;const d=formData();window.open(`https://wa.me/919880336714?text=${encodeURIComponent(compose(d))}`,'_blank','noopener')});
  const year=$('[data-year]');if(year)year.textContent=new Date().getFullYear();
})();